/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CS229_Image */

#ifndef _Included_CS229_Image
#define _Included_CS229_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CS229_Image
 * Method:    Load
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_CS229_1Image_Load
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     CS229_Image
 * Method:    Save
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_CS229_1Image_Save
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     CS229_Image
 * Method:    Convolute
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_CS229_1Image_Convolute
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     CS229_Image
 * Method:    GetPixel
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_CS229_1Image_GetPixel
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     CS229_Image
 * Method:    Free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CS229_1Image_Free
  (JNIEnv *, jobject);

/*
 * Class:     CS229_Image
 * Method:    ReportError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_CS229_1Image_ReportError
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
