//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleNetworkedGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExampleNetworkedGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ace_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Ace_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ace_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Ace_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ace_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Ace_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ace_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Ace_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Big_Joker {
            get {
                object obj = ResourceManager.GetObject("Big_Joker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duece_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Duece_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duece_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Duece_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duece_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Duece_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duece_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Duece_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eight_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Eight_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eight_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Eight_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eight_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Eight_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eight_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Eight_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Five_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Five_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Five_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Five_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Five_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Five_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Five_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Five_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Four_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Four_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Four_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Four_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Four_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Four_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Four_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Four_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Horizontal_Back {
            get {
                object obj = ResourceManager.GetObject("Horizontal_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap King_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("King_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap King_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("King_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap King_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("King_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap King_of_Spades {
            get {
                object obj = ResourceManager.GetObject("King_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Knave_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Knave_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Knave_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Knave_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Knave_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Knave_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Knave_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Knave_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nine_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Nine_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nine_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Nine_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nine_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Nine_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nine_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Nine_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Queen_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Queen_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Queen_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Queen_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Queen_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Queen_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Queen_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Queen_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Seven_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Seven_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Seven_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Seven_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Seven_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Seven_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Seven_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Seven_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Six_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Six_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Six_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Six_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Six_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Six_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Six_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Six_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Small_Joker {
            get {
                object obj = ResourceManager.GetObject("Small_Joker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ten_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Ten_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ten_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Ten_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ten_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Ten_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ten_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Ten_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Three_of_Clubs {
            get {
                object obj = ResourceManager.GetObject("Three_of_Clubs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Three_of_Dimonds {
            get {
                object obj = ResourceManager.GetObject("Three_of_Dimonds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Three_of_Hearts {
            get {
                object obj = ResourceManager.GetObject("Three_of_Hearts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Three_of_Spades {
            get {
                object obj = ResourceManager.GetObject("Three_of_Spades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vertical_Back {
            get {
                object obj = ResourceManager.GetObject("Vertical_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
