; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.21022.08 

	TITLE	c:\Users\The Science Guy\Documents\Visual Studio 2008\Projects\Naomi\Naomi\mmngr_stack.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?StackBase@@3IA					; StackBase
PUBLIC	?StackSize@@3IA					; StackSize
PUBLIC	?old_StackBase@@3IA				; old_StackBase
PUBLIC	?old_StackSize@@3IA				; old_StackSize
_BSS	SEGMENT
?StackBase@@3IA DD 01H DUP (?)				; StackBase
?StackSize@@3IA DD 01H DUP (?)				; StackSize
?old_StackBase@@3IA DD 01H DUP (?)			; old_StackBase
?old_StackSize@@3IA DD 01H DUP (?)			; old_StackSize
_BSS	ENDS
PUBLIC	?mmngr_stack_init@@YAXII@Z			; mmngr_stack_init
EXTRN	?pmmngr_deinit_region@@YAXII@Z:PROC		; pmmngr_deinit_region
; Function compile flags: /Ogtpy
; File c:\users\the science guy\documents\visual studio 2008\projects\naomi\naomi\mmngr_stack.cpp
;	COMDAT ?mmngr_stack_init@@YAXII@Z
_TEXT	SEGMENT
_addr$ = 8						; size = 4
_size$ = 12						; size = 4
?mmngr_stack_init@@YAXII@Z PROC				; mmngr_stack_init, COMDAT

; 18   : 	old_StackBase = addr;

	mov	eax, DWORD PTR _addr$[esp-4]

; 19   : 	old_StackSize = size;

	mov	ecx, DWORD PTR _size$[esp-4]
	mov	DWORD PTR ?old_StackBase@@3IA, eax	; old_StackBase

; 20   : 
; 21   : 	pmmngr_deinit_region(addr - size,size);

	sub	eax, ecx
	mov	DWORD PTR ?old_StackSize@@3IA, ecx	; old_StackSize
	mov	DWORD PTR _size$[esp-4], ecx
	mov	DWORD PTR _addr$[esp-4], eax
	jmp	?pmmngr_deinit_region@@YAXII@Z		; pmmngr_deinit_region
?mmngr_stack_init@@YAXII@Z ENDP				; mmngr_stack_init
_TEXT	ENDS
END
