; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.21022.08 

	TITLE	c:\Users\The Science Guy\Documents\Visual Studio 2008\Projects\Naomi\Naomi\panic.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_0N@PFILFPHL@?$CK?$CK?$CK?5STOP?3?5?$CFs?$AA@ ; `string'
PUBLIC	??_C@_0GE@BBLHKGFN@Kernel?5Panic?$CB?6Unfortunately?5for?5@ ; `string'
PUBLIC	?kernel_panic@@YAXPBDZZ				; kernel_panic
EXTRN	?DebugPrintf@@YAHPBDZZ:PROC			; DebugPrintf
EXTRN	?DebugPuts@@YAXPAD@Z:PROC			; DebugPuts
EXTRN	?DebugSetColor@@YAII@Z:PROC			; DebugSetColor
EXTRN	?DebugGotoXY@@YAXII@Z:PROC			; DebugGotoXY
EXTRN	?DebugClrScr@@YAXG@Z:PROC			; DebugClrScr
EXTRN	?vsprintf@@YAHPADPBDPAE@Z:PROC			; vsprintf
EXTRN	?disable_interrupts@@YAXXZ:PROC			; disable_interrupts
;	COMDAT ?buf@?1??kernel_panic@@YAXPBDZZ@4PADA
; File c:\users\the science guy\documents\visual studio 2008\projects\naomi\naomi\panic.cpp
_BSS	SEGMENT
?buf@?1??kernel_panic@@YAXPBDZZ@4PADA DB 0400H DUP (?)	; `kernel_panic'::`2'::buf
_BSS	ENDS
;	COMDAT ??_C@_0N@PFILFPHL@?$CK?$CK?$CK?5STOP?3?5?$CFs?$AA@
CONST	SEGMENT
??_C@_0N@PFILFPHL@?$CK?$CK?$CK?5STOP?3?5?$CFs?$AA@ DB '*** STOP: %s', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0GE@BBLHKGFN@Kernel?5Panic?$CB?6Unfortunately?5for?5@
CONST	SEGMENT
??_C@_0GE@BBLHKGFN@Kernel?5Panic?$CB?6Unfortunately?5for?5@ DB 'Kernel Pa'
	DB	'nic!', 0aH, 'Unfortunately for you, Naomi OS has encountered', 0aH
	DB	'a fatal error and has to shut down.', 0aH, 0aH, 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ?kernel_panic@@YAXPBDZZ
_TEXT	SEGMENT
_fmt$ = 8						; size = 4
?kernel_panic@@YAXPBDZZ PROC				; kernel_panic, COMDAT

; 14   : 	disable_interrupts();

	call	?disable_interrupts@@YAXXZ		; disable_interrupts

; 15   : 
; 16   : 	va_list args;
; 17   : 	static char buf[1024];
; 18   : 
; 19   : 	va_start(args,fmt);
; 20   : 	vsprintf(buf,fmt,args);

	mov	ecx, DWORD PTR _fmt$[esp-4]
	lea	eax, DWORD PTR _fmt$[esp]
	push	eax
	push	ecx
	push	OFFSET ?buf@?1??kernel_panic@@YAXPBDZZ@4PADA
	call	?vsprintf@@YAHPADPBDPAE@Z		; vsprintf

; 21   : 	va_end(args);
; 22   : 
; 23   : 	char* disclaimer = "Kernel Panic!\nUnfortunately for you, Naomi OS has encountered\na fatal error and has to shut down.\n\n";
; 24   : 
; 25   : 	DebugClrScr(33);

	push	33					; 00000021H
	call	?DebugClrScr@@YAXG@Z			; DebugClrScr

; 26   : 	DebugGotoXY(0,0);

	push	0
	push	0
	call	?DebugGotoXY@@YAXII@Z			; DebugGotoXY

; 27   : 	DebugSetColor(33);

	push	33					; 00000021H
	call	?DebugSetColor@@YAII@Z			; DebugSetColor

; 28   : 
; 29   : 	DebugPuts(disclaimer);

	push	OFFSET ??_C@_0GE@BBLHKGFN@Kernel?5Panic?$CB?6Unfortunately?5for?5@
	call	?DebugPuts@@YAXPAD@Z			; DebugPuts

; 30   : 
; 31   : 	DebugPrintf("*** STOP: %s",buf);

	push	OFFSET ?buf@?1??kernel_panic@@YAXPBDZZ@4PADA
	push	OFFSET ??_C@_0N@PFILFPHL@?$CK?$CK?$CK?5STOP?3?5?$CFs?$AA@
	call	?DebugPrintf@@YAHPBDZZ			; DebugPrintf
	add	esp, 40					; 00000028H
	npad	4
$LL2@kernel_pan:

; 32   : 
; 33   : 	for(;;);

	jmp	SHORT $LL2@kernel_pan
?kernel_panic@@YAXPBDZZ ENDP				; kernel_panic
_TEXT	ENDS
END
