; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.21022.08 

	TITLE	c:\Users\The Science Guy\Documents\Visual Studio 2008\Projects\Naomi\Naomi\sleep.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?sleep@@YAXI@Z					; sleep
EXTRN	?get_tick_count@@YAHXZ:PROC			; get_tick_count
;	COMDAT ?ticks@?1??sleep@@YAXI@Z@4HA
; File c:\users\the science guy\documents\visual studio 2008\projects\naomi\naomi\sleep.cpp
_BSS	SEGMENT
?ticks@?1??sleep@@YAXI@Z@4HA DD 01H DUP (?)		; `sleep'::`2'::ticks
_BSS	ENDS
;	COMDAT ?$S1@?1??sleep@@YAXI@Z@4IA
_BSS	SEGMENT
?$S1@?1??sleep@@YAXI@Z@4IA DD 01H DUP (?)		; `sleep'::`2'::$S1
; Function compile flags: /Ogtpy
_BSS	ENDS
;	COMDAT ?sleep@@YAXI@Z
_TEXT	SEGMENT
_time$ = 8						; size = 4
?sleep@@YAXI@Z PROC					; sleep, COMDAT

; 8    : 	static int ticks = time + get_tick_count();

	mov	eax, 1
	test	BYTE PTR ?$S1@?1??sleep@@YAXI@Z@4IA, al
	jne	SHORT $LL2@sleep
	or	DWORD PTR ?$S1@?1??sleep@@YAXI@Z@4IA, eax
	call	?get_tick_count@@YAHXZ			; get_tick_count
	add	eax, DWORD PTR _time$[esp-4]
	mov	DWORD PTR ?ticks@?1??sleep@@YAXI@Z@4HA, eax
$LL2@sleep:

; 9    : 	while(ticks > get_tick_count());

	call	?get_tick_count@@YAHXZ			; get_tick_count
	cmp	DWORD PTR ?ticks@?1??sleep@@YAXI@Z@4HA, eax
	jg	SHORT $LL2@sleep

; 10   : 
; 11   : 	return;
; 12   : }

	ret	0
?sleep@@YAXI@Z ENDP					; sleep
_TEXT	ENDS
END
