; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.21022.08 

	TITLE	c:\Users\The Science Guy\Documents\Visual Studio 2008\Projects\Naomi\Naomi\vmmngr_pde.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?pd_entry_add_attribute@@YAXPAII@Z		; pd_entry_add_attribute
; Function compile flags: /Ogtpy
; File c:\users\the science guy\documents\visual studio 2008\projects\naomi\naomi\vmmngr_pde.cpp
;	COMDAT ?pd_entry_add_attribute@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attribute$ = 12					; size = 4
?pd_entry_add_attribute@@YAXPAII@Z PROC			; pd_entry_add_attribute, COMDAT

; 14   : 	*e |= attribute;

	mov	eax, DWORD PTR _e$[esp-4]
	mov	ecx, DWORD PTR _attribute$[esp-4]
	or	DWORD PTR [eax], ecx

; 15   : }

	ret	0
?pd_entry_add_attribute@@YAXPAII@Z ENDP			; pd_entry_add_attribute
_TEXT	ENDS
PUBLIC	?pd_entry_del_attribute@@YAXPAII@Z		; pd_entry_del_attribute
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_del_attribute@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attribute$ = 12					; size = 4
?pd_entry_del_attribute@@YAXPAII@Z PROC			; pd_entry_del_attribute, COMDAT

; 19   : 	*e &= ~attribute;

	mov	ecx, DWORD PTR _attribute$[esp-4]
	mov	eax, DWORD PTR _e$[esp-4]
	not	ecx
	and	DWORD PTR [eax], ecx

; 20   : }

	ret	0
?pd_entry_del_attribute@@YAXPAII@Z ENDP			; pd_entry_del_attribute
_TEXT	ENDS
PUBLIC	?pd_entry_set_frame@@YAXPAII@Z			; pd_entry_set_frame
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_set_frame@@YAXPAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
_addr$ = 12						; size = 4
?pd_entry_set_frame@@YAXPAII@Z PROC			; pd_entry_set_frame, COMDAT

; 24   : 	*e |= (*e & ~I86_PDE_FRAME) | addr;

	mov	eax, DWORD PTR _e$[esp-4]
	mov	ecx, DWORD PTR _addr$[esp-4]
	or	DWORD PTR [eax], ecx

; 25   : }

	ret	0
?pd_entry_set_frame@@YAXPAII@Z ENDP			; pd_entry_set_frame
_TEXT	ENDS
PUBLIC	?pd_entry_is_present@@YA_NI@Z			; pd_entry_is_present
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_is_present@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pd_entry_is_present@@YA_NI@Z PROC			; pd_entry_is_present, COMDAT

; 29   : 	return e & I86_PDE_PRESENT;

	mov	eax, DWORD PTR _e$[esp-4]
	and	eax, 1

; 30   : }

	ret	0
?pd_entry_is_present@@YA_NI@Z ENDP			; pd_entry_is_present
_TEXT	ENDS
PUBLIC	?pd_entry_is_user@@YA_NI@Z			; pd_entry_is_user
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_is_user@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pd_entry_is_user@@YA_NI@Z PROC				; pd_entry_is_user, COMDAT

; 34   : 	return e & I86_PDE_USER;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 2
	and	al, 1

; 35   : }

	ret	0
?pd_entry_is_user@@YA_NI@Z ENDP				; pd_entry_is_user
_TEXT	ENDS
PUBLIC	?pd_entry_is_4mb@@YA_NI@Z			; pd_entry_is_4mb
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_is_4mb@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pd_entry_is_4mb@@YA_NI@Z PROC				; pd_entry_is_4mb, COMDAT

; 39   : 	return e & I86_PDE_4MB;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 7
	and	al, 1

; 40   : }

	ret	0
?pd_entry_is_4mb@@YA_NI@Z ENDP				; pd_entry_is_4mb
_TEXT	ENDS
PUBLIC	?pd_entry_is_writable@@YA_NI@Z			; pd_entry_is_writable
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_is_writable@@YA_NI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pd_entry_is_writable@@YA_NI@Z PROC			; pd_entry_is_writable, COMDAT

; 44   : 	return e & I86_PDE_WRITABLE;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 1
	and	al, 1

; 45   : }

	ret	0
?pd_entry_is_writable@@YA_NI@Z ENDP			; pd_entry_is_writable
_TEXT	ENDS
PUBLIC	?pd_entry_pfn@@YAII@Z				; pd_entry_pfn
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_pfn@@YAII@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pd_entry_pfn@@YAII@Z PROC				; pd_entry_pfn, COMDAT

; 49   : 	return e & I86_PDE_FRAME;

	mov	eax, DWORD PTR _e$[esp-4]
	and	eax, 2147479552				; 7ffff000H

; 50   : }

	ret	0
?pd_entry_pfn@@YAII@Z ENDP				; pd_entry_pfn
_TEXT	ENDS
PUBLIC	?pd_entry_enable_global@@YAXI@Z			; pd_entry_enable_global
; Function compile flags: /Ogtpy
;	COMDAT ?pd_entry_enable_global@@YAXI@Z
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pd_entry_enable_global@@YAXI@Z PROC			; pd_entry_enable_global, COMDAT

; 53   : {}

	ret	0
?pd_entry_enable_global@@YAXI@Z ENDP			; pd_entry_enable_global
_TEXT	ENDS
END
